### PR TITLE
Search + pagination

### PR DESCRIPTION
**Pull request by hizmailovich**

### CODE REVIEW

**Review by h1alexbel — COMMENTED** [review]
@hizmailovich do you have an integration test for this logic?

**Review by h1alexbel — COMMENTED** [review]
@hizmailovich do you have an integration test for this logic?

**Comment by hizmailovich** [comment]
No, but I can add an integration test for elasticsearch

**Comment by h1alexbel** [comment]
@hizmailovich Sure, do it
we need to verify whether it's working or not

**Review by h1alexbel — APPROVED** [review]

**Comment by h1alexbel** [comment]
@rultor merge

**Comment by hizmailovich** [comment]
@rultor merge

**Pull request merged**
